---
# read-only mode on master server
- name: read-only on new master server
  mysql_variables:
    variable=read_only
    value=1
    login_unix_socket={{ mysql_socket }}
  delegate_to: "{{ new_master_server  }}"
  tags: mysql
  run_once: true

- name: master option from replacement
  mysql_replication:
    mode=getmaster
    login_unix_socket={{ mysql_socket }}
  delegate_to: "{{ new_master_server }}"
  register: master_status
  tags: mysql

- name: stop slave
  mysql_replication:
    mode={{ item }}
    login_unix_socket={{ mysql_socket }}
  tags: mysql
  ignore_errors: true
  with_items:
    - stopslave
    - resetslave

- name: change master
  mysql_replication:
    mode=changemaster
    master_host={{ new_master_server }}
    master_log_file={{ master_status.File }}
    master_log_pos={{ master_status.Position }}
    master_user={{ replica_login }}
    master_password={{ replica_password }}
    master_ssl_ca=/var/lib/mysql/ca.pem
    master_ssl_cert=/var/lib/mysql/server.crt
    master_ssl_key=/var/lib/mysql/server.key
  tags: mysql

- name: start replication 
  mysql_replication:
    mode=startslave
  tags: mysql

- name: read-write on new master server
  delegate_to: "{{ new_master_server }}"
  mysql_variables:
    variable=read_only
    value=0
    login_unix_socket={{ mysql_socket  }}
  tags: mysql
  run_once: true
