---
# update mysql service to 5.7 version
- name: install package
  yum:
    name: bzip2
    state: latest

- include_tasks: common-etckeeper.yml
  when: "slave_server == inventory_hostname or master_server == inventory_hostname"

- include_tasks: sites-gathering_facts-not_mandatory.yml

- include_tasks: backup_dbs.yml
  when: "proccess_sites and inventory_hostname == master_server"

- name: additional gathering facts
  bx_vat:

- set_fact: 
    my_mid_version: "{{ mysql_mid_version }}" 

- include_tasks: upgrade_mysql56.yml
  when: "mysql_uni_version == '55'"

- set_fact: 
    my_mid_version: "{{ mysql_mid_version }}" 

- include_tasks: upgrade_mysql57.yml
  when: "mysql_uni_version == '56'"

- name: remove backup files
  file: 
    path: "{{item}}"
    state: absent
  with_fileglob:
    - "/etc/my.cnf.ori*"
    - "/etc/my.cnf.rpm*"
    - "/etc/my.cnf.bx_mysql*"
  ignore_errors: yes

