---
- include_tasks: shutdown_mysqld.yml

- name: remove installed mysql
  shell: rpm -e --nodeps MariaDB-client MariaDB-common MariaDB-server MariaDB-shared
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
 
- name: remove installed mysql
  shell: rpm -e --nodeps mysql mysql-libs mysql-server
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: clean outdated configs
  file:
    path="{{ item }}"
    state=absent 
  with_items:
    - /etc/systemd/system/mysqld.service
    - /etc/systemd/system/mysql.service
    - /etc/systemd/system/mariadb.service.d
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: configure Percona repository
  yum: 
    name: "http://repo.percona.com/release/percona-release-latest.noarch.rpm"
    state: present
  tags: yum

- name: enable Percona repository
  ini_file:
    dest: /etc/yum.repos.d/percona-release.repo
    section: "percona-release-$basearch"
    option: enabled
    value: 1
    backup: yes

- name: update percona-release package
  shell: yum -y --nogpg update percona-release

- name: install Percona packages
  yum: 
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - Percona-Server-client-56
      - Percona-Server-server-56
      - Percona-Server-shared-56
  tags: yum

- name: additional gathering facts
  bx_vat:

- name: restore my.cnf
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf 
    mode=0644
    owner=root
    group=mysql
  tags: mysql

- name: create run directory
  file:
    path=/var/run/mysqld
    state=directory
    owner=mysql
    group=mysql
  tags: mysql

- name: create mysqld service
  file:
    src=/etc/init.d/mysql
    dest=/etc/init.d/mysqld
    state=link
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: generate mysql private key
  shell: cd /var/lib/mysql && openssl genrsa -out private_key.pem 2048
  args: 
    creates: /var/lib/mysql/private_key.pem
  tags: mysql

- name: generate mysql public key
  shell: cd /var/lib/mysql && openssl rsa -in private_key.pem -pubout -out public_key.pem
  args:
    creates: /var/lib/mysql/public_key.pem
  tags: mysql

- name: access rights for mysql keys
  file: path={{ item }}
    owner=mysql
    group=mysql
  with_items:
    - /var/lib/mysql/private_key.pem
    - /var/lib/mysql/public_key.pem

- include_tasks: upgrade_dbs.yml

- include_tasks: upgrade_bvat.yml

- name: enable mysqld service
  service:
    name=mysqld
    state=started
    enabled=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


