---
- name: update bvat service
  lineinfile:
    dest: /etc/systemd/system/bvat.service
    regexp: "After=mariadb.service"
    line: "After=mysqld.service"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: upgrade systemd info
  shell: systemctl daemon-reload
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
