---
- name: Install RpmFusion repo
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm"

- name: Install Ffmpeg
  yum:
    name: ffmpeg
    state: present
