---
- name: delete include
  lineinfile:
    dest: "/etc/nginx/bx/site_enabled/http_balancer.conf"
    regexp: "letsencrypt-challenge-tokens.conf;$"
    state: absent

- name: update site config
  lineinfile:
    dest: "/etc/nginx/bx/site_enabled/http_balancer.conf"
    insertafter: "proxy_set_header"
    line: "include bx/conf/letsencrypt-challenge-tokens.conf;"


