---
# lsync_server: cluster_web_server
# lsync_site: web_site_name
- name: update lsyncd config on master
  delegate_to: "{{ cluster_web_server }}"
  blockinfile:
    marker: "-- {mark} settings for {{ web_site_name }}"
    dest: "/etc/lsyncd-{{ inventory_hostname }}.conf"
    state: absent
  when: "'bitrix-web' in group_names and inventory_hostname != cluster_web_server"

- name: restart service lsyncd
  delegate_to: "{{ cluster_web_server }}"
  service:
    name=lsyncd-{{ inventory_hostname }}
    state=started
    enabled=yes
  when: "'bitrix-web' in group_names and inventory_hostname != cluster_web_server"
  run_once: true

- name: update lsyncd config on master
  blockinfile:
    marker: "-- {mark} settings for {{ web_site_name }}"
    dest: "/etc/lsyncd-{{ cluster_web_server }}.conf"
    state: absent
  when: "'bitrix-web' in group_names and inventory_hostname != cluster_web_server"

- name: restart service lsyncd
  service:
    name=lsyncd-{{ cluster_web_server }}
    state=started
    enabled=yes
  when: "'bitrix-web' in group_names and inventory_hostname != cluster_web_server"
