---
- include: /etc/ansible/inc_vars.yml

- name: additional gathering facts
  bx_vat: 

# manage sites
- include: create_link.yml
  when: "manage_web == 'create_site' and web_site_type == 'link'"
  static: no

- include: create_kernel.yml
  when: "manage_web == 'create_site' and web_site_type == 'kernel'"
  static: no

- include: create_ext_kernel.yml
  when: "manage_web == 'create_site' and web_site_type == 'ext_kernel'"
  static: no

- include: delete_site.yml
  when: "manage_web == 'delete_site'"
  static: no

# php7 tasks
- include: upgrade_php7.yml
  when: "manage_web == 'upgrade_php7'"
  static: no

- include: upgrade_php71.yml
  when: "manage_web == 'upgrade_php71'"
  static: no

- include: upgrade_php72.yml
  when: "manage_web == 'upgrade_php72'"
  static: no

- include: rollback_php7.yml
  when: "manage_web == 'rollback_php7'"
  static: no

- include: rollback_php70.yml
  when: "manage_web == 'rollback_php70'"
  static: no

- include: rollback_php71.yml
  when: "manage_web == 'rollback_php71'"
  static: no

# web cluster configuration
- include: delete_web.yml
  when: "manage_web == 'delete_web'"
  static: no

- include: web1.yml
  when: "manage_web == 'web1' or manage_web == 'create_web'"
  static: no

- include: web2.yml
  when: "manage_web == 'web2' or manage_web == 'create_web'"
  static: no

# certificates
- include: configure_le.yml
  when: "manage_web == 'configure_le' and inventory_hostname == cluster_web_server"
  static: no

- include: configure_cert.yml
  when: "manage_web == 'configure_cert' and inventory_hostname == cluster_web_server"
  static: no

- include: reset_cert.yml
  when: "manage_web == 'reset_cert' and inventory_hostname == cluster_web_server"
  static: no

# other
- include: web_composite_configs.yml
  when: "manage_web == 'enable_composite' or manage_web == 'disable_composite'"
  static: no

- include: create_ntlm.yml
  when: "manage_web == 'ntlm_on' and inventory_hostname == cluster_web_server"
  static: no

- include: restart_web.yml
  when: "manage_web == 'restart_web'"
  static: no

- include: php_ext.yml
  when: "manage_web == 'php_extension' and 'bitrix-web' in group_names"
  static: no

- include: site_options.yml
  when: "manage_web == 'site_options' and 'bitrix-web' in group_names"
  static: no

- name: delete temporary config
  file: path="{{ ansible_playbook_file }}" state=absent
  when: "ansible_playbook_file != 'NOT_DEFINED'"
