---
# enable monitoring fo web nodes
- name: nginx config for sub status in site_available
  template: src=nginx/nginx_server_status.conf.j2
    dest="{{ nginx_base_dir }}/{{ nginx_available_sites_dir }}/nginx_server_status.conf"
    owner="{{ site_bitrix }}" group="{{ site_root }}" mode=0664
  tags: monitor
  notify: restart nginx

- name: nginx config for sub status in site_enable
  file: src="{{ nginx_base_dir }}/{{ nginx_available_sites_dir }}/nginx_server_status.conf"
    dest="{{ nginx_base_dir }}/{{ nginx_enabled_sites_dir }}/nginx_server_status.conf"
    state=link
  tags: monitor
  notify: restart nginx

- name: enable web-service plugins
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - apache_accesses
    - apache_processes
    - apache_volume
    - nginx_request
    - nginx_status
  tags: monitor

- name: enable process monitoring plugins
  file: src=/usr/share/munin/plugins/process_status_
    dest=/etc/munin/plugins/process_status_{{ item }}
    state=link
  with_items:
    - httpd
    - nginx
  tags: monitor

- name: restart munin-node service
  service: name=munin-node state=restarted
  tags: monitor
