---
# 1. copy /etc/php.d files
# 3. remove current version php
# 4. install old version php
# 5. restart httpd
- shell: rsync -a --delete /etc/php.d/ /opt/webdir/tmp/php.d/
  args:
    creates: /opt/webdir/tmp/php.d/bitrixenv.ini

- name: enable remi php70 repository
  ini_file: 
    dest: /etc/yum.repos.d/remi-php70.repo
    section: remi-php70
    option: enabled
    value: 1
  tags: remi

- name: disable remi php71 repository
  ini_file: 
    dest: /etc/yum.repos.d/remi-php71.repo
    section: remi-php71
    option: enabled
    value: 0
  tags: remi

- include_tasks: reinstall_php.yml
  vars:
    is_php71: false
    is_php56: false

- include: php_ext_dublicates.yml

- name: restart httpd
  service: name=httpd state=restarted

