---
# 1. copy /etc/php.d files
# 3. remove current version php
# 4. install old version php
# 5. restart httpd
- shell: rsync -a --delete /etc/php.d/ /opt/webdir/tmp/php.d/
  args:
    creates: /opt/webdir/tmp/php.d/bitrixenv.ini

- name: enable remi php73 repository
  ini_file: 
    dest: /etc/yum.repos.d/remi-php73.repo
    section: remi-php73
    option: enabled
    value: 1
  tags: remi

- name: disable remi php74 repository
  ini_file: 
    dest: /etc/yum.repos.d/remi-php74.repo
    section: remi-php74
    option: enabled
    value: 0
  tags: remi

- include_tasks: reinstall_php.yml
  vars:
    is_php71: false
    is_php56: false

- include_tasks: php_ext_dublicates.yml

- name: convert extension names
  shell: /opt/webdir/bin/convert_phpd_files.sh

- name: restart httpd
  service:
    name=httpd
    state=restarted
