---
- yum:
    name: iptables-services
    state: present

- service:
    name: firewalld
    enabled: no
    state: stopped
  ignore_errors: true

- include_tasks: iptables-executer.yml

- service:
    name: iptables
    enabled: yes
    state: started
