---
# configure oldkernel limits
- name: get server options
  bx_vat:

- name: install yum-utils
  yum:
    name: yum-utils
    state: latest
  when: "inventory_hostname == common_server or common_server == 'NOT_DEFINED'"

- name: remove old value installonly_limit options
  lineinfile:
    dest: /etc/yum.conf
    line: installonly_limit=5
    state: absent
  when: "inventory_hostname == common_server or common_server == 'NOT_DEFINED'"

- name: configure installonly_limit options
  lineinfile:
    dest: /etc/yum.conf
    line: installonly_limit=3
  when: "inventory_hostname == common_server or common_server == 'NOT_DEFINED'"

- name: delete old kernels
  shell: package-cleanup --oldkernels --count=3 -y
  when: "inventory_hostname == common_server or common_server == 'NOT_DEFINED'"

- name: clean yum info
  shell: yum clean all
  tags: yum_update
  when: "inventory_hostname == common_server or common_server == 'NOT_DEFINED'"

# configure percona repository
- name: update percona release
  shell: yum -y --nogpg update percona-release
  when: mysql_package == 'Percona-Server-server'

- name: update all packages
  yum:
    pkg: '*'
    state: latest
  tags: yum_update
  when: "inventory_hostname == common_server or common_server == 'NOT_DEFINED'"
