---
# handle for web-service nginx
- name: restart nginx
  service:
    state: reloaded
    name: nginx

# apache/httpd
- name: restart httpd
  service:
    state: restarted
    name: httpd

- name: restart httpd-scale
  shell: /opt/webdir/bin/restart_httpd-scale.sh
  args:
    creates: /opt/webdir/logs/restart_httpd-scale.request

# systemd-tmpfiles
- name: systemd-tmpfiles-create
  shell: systemd-tmpfiles --create 
